=== fortunkam/QuizzR/QuizExperiment.Models/v1Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Quiz",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the quiz"
    },
    "title": {
      "type": "string",
      "description": "Title of the quiz"
    },
    "description": {
      "type": "string",
      "description": "Description of the quiz"
    },
    "userid": {
      "type": "string",
      "description": "User ID of the quiz creator"
    },
    "questions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "imageUrl": {
            "type": "string",
            "format": "uri"
          },
          "timeout": {
            "type": "integer"
          },
          "options": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "correctAnswerIndex": {
            "type": "integer"
          }
        },
        "required": [
          "title",
          "imageUrl",
          "timeout",
          "options",
          "correctAnswerIndex"
        ]
      }
    },
    "folderPath": {
      "type": [ "string", "null" ],
      "description": "Optional folder path"
    }
  },
  "required": [
    "id",
    "title",
    "description",
    "userid",
    "questions",
    "folderPath"
  ]
}

=== fortunkam/QuizzR/QuizExperiment.Models.Test/TestData/v1SchemaQuestionSet.json
{
  "id": "b395c553-56c4-42d0-97d4-a104caf2f847",
  "title": "Test 2",
  "description": "",
  "userid": "5694c6de-add8-412f-b1c7-a9e5c7ca9945",
  "questions": [
    {
      "title": "what colour is the sky?",
      "imageUrl": "https://media4.giphy.com/media/v1.Y2lkPWVmNGIzMjZjaW01djJqbnI2bG1rNmppaWtnamk0MzNidXh1NXpreWEwMXlqZjhsdiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Pp9W9tuVF5NwQ/giphy.gif",
      "timeout": 20,
      "options": [
        "green",
        "red",
        "blue",
        "unknown"
      ],
      "correctAnswerIndex": 2
    },
    {
      "title": "What is the main purpose of Azure Functions?",
      "imageUrl": "https://media1.giphy.com/media/v1.Y2lkPWVmNGIzMjZjMzdsOGNjZ293enZyN2ZjY3I5YnRidnY0eWl6MTJ4bTU4bm94aG9ycSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/fmkYSBlJt3XjNF6p9c/giphy.gif",
      "timeout": 20,
      "options": [
        "To host virtual machines in the cloud",
        "To manage and analyze large datasets",
        "To run event-driven serverless code",
        "To create and manage virtual networks"
      ],
      "correctAnswerIndex": 2
    }
  ],
  "folderPath": null
}
